// HybriMax.idl : IDL source for HybriMax
//

// This file will be processed by the MIDL tool to
// produce the type library (HybriMax.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(5D24FBBC-6316-4991-B198-9C570C9538DC),
	version(1.0),
]
library HybriMaxLib
{
	importlib("stdole2.tlb");
};

